//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MsgLockStep.proto
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Opts")]
  public partial class Opts : global::ProtoBuf.IExtensible
  {
    public Opts() {}
    
    private uint _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private Operation _operation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Operation operation
    {
      get { return _operation; }
      set { _operation = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _param = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(3, Name=@"param", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> param
    {
      get { return _param; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLockStep")]
  public partial class MsgLockStep : global::ProtoBuf.IExtensible
  {
    public MsgLockStep() {}
    
    private string _protoName = @"MsgLockStep";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"protoName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"MsgLockStep")]
    public string protoName
    {
      get { return _protoName; }
      set { _protoName = value; }
    }
    private int _turn = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"turn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int turn
    {
      get { return _turn; }
      set { _turn = value; }
    }
    private readonly global::System.Collections.Generic.List<Opts> _opts = new global::System.Collections.Generic.List<Opts>();
    [global::ProtoBuf.ProtoMember(3, Name=@"opts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Opts> opts
    {
      get { return _opts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Operation")]
    public enum Operation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Joystick", Value=0)]
      Joystick = 0
    }
  
}