//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MsgLockStepBack.proto
// Note: requires additional types generated from: proto/MsgLockStep.proto
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnsyncOpts")]
  public partial class UnsyncOpts : global::ProtoBuf.IExtensible
  {
    public UnsyncOpts() {}
    
    private int _turn = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"turn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int turn
    {
      get { return _turn; }
      set { _turn = value; }
    }
    private readonly global::System.Collections.Generic.List<Opts> _opts = new global::System.Collections.Generic.List<Opts>();
    [global::ProtoBuf.ProtoMember(2, Name=@"opts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Opts> opts
    {
      get { return _opts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLockStepBack")]
  public partial class MsgLockStepBack : global::ProtoBuf.IExtensible
  {
    public MsgLockStepBack() {}
    
    private int _turn = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"turn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int turn
    {
      get { return _turn; }
      set { _turn = value; }
    }
    private readonly global::System.Collections.Generic.List<UnsyncOpts> _unsyncOpts = new global::System.Collections.Generic.List<UnsyncOpts>();
    [global::ProtoBuf.ProtoMember(2, Name=@"unsyncOpts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UnsyncOpts> unsyncOpts
    {
      get { return _unsyncOpts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}